#!/bin/bash

shopt -s nullglob

to=$1
cubicle=$2
pathcub=$3
score=0
score_s=0
score_u=0
score_t=0
max=0

for f in $3*.cub; do
    echo $f;
    max=`expr $max + 1`;
    T="$(date +%s%N)"

    # Do some work here
    timeout $to $cubicle $f > /dev/null 2>&1;
    res=$?;
    
    # Time interval in nanoseconds
    T="$(($(date +%s%N)-T))"
    # Seconds
    S="$((T/1000000000))"
    # Milliseconds
    M="$((T/1000000))"

    printf "    Time : %02d:%02d.%03d\n" "$((S/60%60))" "$((S%60))" "${M}"

    case $res in
	"1") 
	    echo "    UNSAFE";
            score_u=`expr $score_u + 1`;
            score=`expr $score + 1`;;
        "0") 
	    echo "    SAFE";
            score_s=`expr $score_s + 1`;
            score=`expr $score + 1`;;
	*)
 	score_t=`expr $score_t + 1`;
	echo "    Timeout";;
    esac
done

percent=`expr 100 \* $score / $max`; 
percent_s=`expr 100 \* $score_s / $max`; 
percent_u=`expr 100 \* $score_u / $max`; 
percent_t=`expr 100 \* $score_t / $max`; 

echo "Results  : $score/$max = $percent%"; 
echo "Safe     : $score_s/$max = $percent_s%";
echo "Unsafe   : $score_u/$max = $percent_u%";
echo "Timeouts : $score_t/$max = $percent_t%";
