.TH Cubicle "August, 2011"

.SH NAME
Cubicle \- Combining model checking algorithms and SMT solvers


.SH SYNOPSIS
.B cublic
[
.B options
]
.B files


.SH DESCRIPTION

.B Cubicle
is a model checker for array-based systems. It combines model
checking algorithms and automatic SMT theorem provers.

.SH OPTIONS

.TP
.B \-h
Help. Will give you the full list of command line options.

